---
default_context:
  scenario_name: "default"
  email: "bossjones@theblacktonystark.com"
  github_user: "bossjones"
  release_date: "2018-02-12"
  year: "2018"
  version: "0.1.0"
  min_ansible_version: "2.3.2.0"
  allow_duplicates: "no"
  license: "Apache"
  company: "Tony Dark Labs"
  os_user: "vagrant"
  author_name: "Malcolm Jones"
  author: "Malcolm Jones"
  author_email: "bossjones@theblacktonystark.com"
  domain_name: "theblacktonystark.com"
cookiecutters_dir: "~/.cookiecutters/"

