---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:16.04
    privileged: true
provisioner:
  name: ansible
  # options:
  #   vvv: True
  lint:
    name: ansible-lint
    # EANSIBLE0013 should not be raised for shell tasks that use globs.
    options:
      x: ANSIBLE0013
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    enabled: False
scenario:
  name: {{ cookiecutter.scenario_name }}
  # test_sequence:
  #   - destroy
  #   - syntax
  #   - create
  #   - prepare
  #   - converge
  #   - lint
  #   - side_effect
  #   - verify
  #   - destroy

  test_sequence:
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - lint
    - side_effect
    - verify
    - destroy
