{% if cookiecutter.use_gilt == "yes" %}
{% raw %}
---
dependency:
  name: gilt
# delegate example: https://github.com/freedomofpress/securedrop/blob/30257872db2ccad24141ff24269ff2f959a519fd/molecule/builder/create.yml
{% endraw %}
{% elif cookiecutter.use_gilt == "no" %}
---
{% endif %}

{% if cookiecutter.use_delegated == "yes" %}
{% raw %}
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'docker exec --user vagrant --tty -ti {instance} env TERM=xterm bash'
    ansible_connection_options:
      ansible_connection: docker
{% endraw %}
{% elif cookiecutter.use_delegated == "no" %}
{% raw %}
driver:
  name: docker
{% endraw %}
{% endif %}
dependency:
  name: galaxy
lint:
  name: yamllint
  enabled: False
{% if cookiecutter.use_delegated == "yes" %}
platforms:
  # source: https://blog.opsfactory.rocks/testing-ansible-roles-with-molecule-97ceca46736a
  # source: https://github.com/solita/docker-systemd
  # source: https://github.com/solita/docker-systemd-ssh/blob/master/Dockerfile
  - name: {{ cookiecutter.repo_name }}-{{ cookiecutter.docker_container_flavor }}
{% elif cookiecutter.use_delegated == "no" %}
platforms:
  # source: https://blog.opsfactory.rocks/testing-ansible-roles-with-molecule-97ceca46736a
  # source: https://github.com/solita/docker-systemd
  # source: https://github.com/solita/docker-systemd-ssh/blob/master/Dockerfile
  # start_command: docker run -d --name systemd --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd
  - name: {{ cookiecutter.repo_name }}-{{ cookiecutter.docker_container_flavor }}
    image: solita/ubuntu-systemd
    image_version: latest
    privileged: True
    groups:
        - servers
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
  # - name: fedora-01
  #   image: bossjones/fedora24-systemd-ansible:latest
  #   privileged: True
  #   command: /usr/sbin/init
  #   # run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   # init: /usr/lib/systemd/systemd
  #   groups:
  #     - fedora
  # TODO: USE THESES
  # SOURCE: https://zapier.com/engineering/ansible-molecule/
  #   - name: centos7
  #   image: retr0h/centos7-systemd-ansible
  #   image_version: latest
  #   privileged: True
  # - name: consul-ubuntu-16.04
  #   image: solita/ubuntu-systemd
  #   image_version: latest
  #   privileged: True
  # - name: consul-ubuntu-14.04
  #   image: ubuntu-upstart
  #   image_version: latest
  #   privileged: True
{% endif %}

{% if cookiecutter.use_delegated == "yes" %}
provisioner:
  name: ansible
  playbooks:
    prepare: ''
    create: ''
  options:
    vvv: True
{% elif cookiecutter.use_delegated == "no" %}
provisioner:
  name: ansible
{% endif %}
  lint:
    name: ansible-lint
    enabled: False
    # EANSIBLE0013 should not be raised for shell tasks that use globs.
    options:
      x: ANSIBLE0013

verifier:
  name: testinfra
  options:
    verbose: True
  lint:
    name: flake8
    enabled: False

{% if cookiecutter.use_delegated == "yes" %}
scenario:
  name: {{ cookiecutter.scenario_name }}
  test_sequence:
    - destroy
    - dependency
    - create
    - converge
    - verify
    - destroy
{% elif cookiecutter.use_delegated == "no" %}
scenario:
  name: {{ cookiecutter.scenario_name }}
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - lint
    - side_effect
    - verify
    - destroy
{% endif %}


