---
- name: Converge
  hosts: all
{%- if cookiecutter.run_ansible_as_root == "yes" %}
  become: yes
  become_method: sudo
{%- endif %}
  environment:
    SHELL: /bin/bash
  roles:
    - role: boss-ansible-role-core
    - role: boss-ansible-role-fact
    - role: boss-ansible-role-environment

    - role: {{ cookiecutter.repo_name }}
{%- if cookiecutter.run_ansible_as_root == "yes" %}
      bossjones__user: root
      bossjones__group: root
{% elif cookiecutter.run_ansible_as_root == "no" %}
      bossjones__user: {{ cookiecutter.os_user }}
      bossjones__group: {{ cookiecutter.os_user }}
{%- endif %}

